require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MenController do

  # This should return the minimal set of attributes required to create a valid
  # Man. As you add validations to Man, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "full_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MenController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all men as @men" do
      man = Man.create! valid_attributes
      get :index, {}, valid_session
      assigns(:men).should eq([man])
    end
  end

  describe "GET show" do
    it "assigns the requested man as @man" do
      man = Man.create! valid_attributes
      get :show, {:id => man.to_param}, valid_session
      assigns(:man).should eq(man)
    end
  end

  describe "GET new" do
    it "assigns a new man as @man" do
      get :new, {}, valid_session
      assigns(:man).should be_a_new(Man)
    end
  end

  describe "GET edit" do
    it "assigns the requested man as @man" do
      man = Man.create! valid_attributes
      get :edit, {:id => man.to_param}, valid_session
      assigns(:man).should eq(man)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Man" do
        expect {
          post :create, {:man => valid_attributes}, valid_session
        }.to change(Man, :count).by(1)
      end

      it "assigns a newly created man as @man" do
        post :create, {:man => valid_attributes}, valid_session
        assigns(:man).should be_a(Man)
        assigns(:man).should be_persisted
      end

      it "redirects to the created man" do
        post :create, {:man => valid_attributes}, valid_session
        response.should redirect_to(Man.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved man as @man" do
        # Trigger the behavior that occurs when invalid params are submitted
        Man.any_instance.stub(:save).and_return(false)
        post :create, {:man => { "full_name" => "invalid value" }}, valid_session
        assigns(:man).should be_a_new(Man)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Man.any_instance.stub(:save).and_return(false)
        post :create, {:man => { "full_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested man" do
        man = Man.create! valid_attributes
        # Assuming there are no other men in the database, this
        # specifies that the Man created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Man.any_instance.should_receive(:update_attributes).with({ "full_name" => "MyString" })
        put :update, {:id => man.to_param, :man => { "full_name" => "MyString" }}, valid_session
      end

      it "assigns the requested man as @man" do
        man = Man.create! valid_attributes
        put :update, {:id => man.to_param, :man => valid_attributes}, valid_session
        assigns(:man).should eq(man)
      end

      it "redirects to the man" do
        man = Man.create! valid_attributes
        put :update, {:id => man.to_param, :man => valid_attributes}, valid_session
        response.should redirect_to(man)
      end
    end

    describe "with invalid params" do
      it "assigns the man as @man" do
        man = Man.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Man.any_instance.stub(:save).and_return(false)
        put :update, {:id => man.to_param, :man => { "full_name" => "invalid value" }}, valid_session
        assigns(:man).should eq(man)
      end

      it "re-renders the 'edit' template" do
        man = Man.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Man.any_instance.stub(:save).and_return(false)
        put :update, {:id => man.to_param, :man => { "full_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested man" do
      man = Man.create! valid_attributes
      expect {
        delete :destroy, {:id => man.to_param}, valid_session
      }.to change(Man, :count).by(-1)
    end

    it "redirects to the men list" do
      man = Man.create! valid_attributes
      delete :destroy, {:id => man.to_param}, valid_session
      response.should redirect_to(men_url)
    end
  end

end
