require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WomenController do

  # This should return the minimal set of attributes required to create a valid
  # Woman. As you add validations to Woman, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "full_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WomenController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all women as @women" do
      woman = Woman.create! valid_attributes
      get :index, {}, valid_session
      assigns(:women).should eq([woman])
    end
  end

  describe "GET show" do
    it "assigns the requested woman as @woman" do
      woman = Woman.create! valid_attributes
      get :show, {:id => woman.to_param}, valid_session
      assigns(:woman).should eq(woman)
    end
  end

  describe "GET new" do
    it "assigns a new woman as @woman" do
      get :new, {}, valid_session
      assigns(:woman).should be_a_new(Woman)
    end
  end

  describe "GET edit" do
    it "assigns the requested woman as @woman" do
      woman = Woman.create! valid_attributes
      get :edit, {:id => woman.to_param}, valid_session
      assigns(:woman).should eq(woman)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Woman" do
        expect {
          post :create, {:woman => valid_attributes}, valid_session
        }.to change(Woman, :count).by(1)
      end

      it "assigns a newly created woman as @woman" do
        post :create, {:woman => valid_attributes}, valid_session
        assigns(:woman).should be_a(Woman)
        assigns(:woman).should be_persisted
      end

      it "redirects to the created woman" do
        post :create, {:woman => valid_attributes}, valid_session
        response.should redirect_to(Woman.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved woman as @woman" do
        # Trigger the behavior that occurs when invalid params are submitted
        Woman.any_instance.stub(:save).and_return(false)
        post :create, {:woman => { "full_name" => "invalid value" }}, valid_session
        assigns(:woman).should be_a_new(Woman)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Woman.any_instance.stub(:save).and_return(false)
        post :create, {:woman => { "full_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested woman" do
        woman = Woman.create! valid_attributes
        # Assuming there are no other women in the database, this
        # specifies that the Woman created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Woman.any_instance.should_receive(:update_attributes).with({ "full_name" => "MyString" })
        put :update, {:id => woman.to_param, :woman => { "full_name" => "MyString" }}, valid_session
      end

      it "assigns the requested woman as @woman" do
        woman = Woman.create! valid_attributes
        put :update, {:id => woman.to_param, :woman => valid_attributes}, valid_session
        assigns(:woman).should eq(woman)
      end

      it "redirects to the woman" do
        woman = Woman.create! valid_attributes
        put :update, {:id => woman.to_param, :woman => valid_attributes}, valid_session
        response.should redirect_to(woman)
      end
    end

    describe "with invalid params" do
      it "assigns the woman as @woman" do
        woman = Woman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Woman.any_instance.stub(:save).and_return(false)
        put :update, {:id => woman.to_param, :woman => { "full_name" => "invalid value" }}, valid_session
        assigns(:woman).should eq(woman)
      end

      it "re-renders the 'edit' template" do
        woman = Woman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Woman.any_instance.stub(:save).and_return(false)
        put :update, {:id => woman.to_param, :woman => { "full_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested woman" do
      woman = Woman.create! valid_attributes
      expect {
        delete :destroy, {:id => woman.to_param}, valid_session
      }.to change(Woman, :count).by(-1)
    end

    it "redirects to the women list" do
      woman = Woman.create! valid_attributes
      delete :destroy, {:id => woman.to_param}, valid_session
      response.should redirect_to(women_url)
    end
  end

end
